In [26]:
import pandas as pd
import numpy as np

In [27]:
data = np.random.randint(0, 100, [1000, 50])
data

array([[64, 71, 40, ..., 40, 30, 28],
       [ 6, 44, 23, ..., 96, 23, 73],
       [68, 26, 13, ..., 60, 93, 69],
       ...,
       [99, 65, 72, ..., 64, 32, 61],
       [79, 67, 39, ..., 63, 62, 64],
       [90, 77, 65, ..., 94, 98, 13]])

In [28]:
df = pd.DataFrame(data)
df

     0   1   2   3   ...  46  47  48  49
0    64  71  40   3  ...  23  40  30  28
1     6  44  23  24  ...  20  96  23  73
2    68  26  13  86  ...  79  60  93  69
..   ..  ..  ..  ..  ...  ..  ..  ..  ..
997  99  65  72  45  ...  83  64  32  61
998  79  67  39  55  ...  57  63  62  64
999  90  77  65  26  ...  48  94  98  13

[1000 rows x 50 columns]

In [16]:
pd.options.display.max_rows= 6

In [17]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,11,25,30,63,11,83,83,21,63,89,...,47,93,32,51,21,98,78,87,67,96
1,97,9,63,70,60,69,95,60,80,91,...,46,66,79,36,41,92,10,60,17,89
2,17,93,64,93,71,59,91,30,26,34,...,94,46,28,37,75,16,94,63,78,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,32,0,31,38,91,81,54,86,2,18,...,58,21,90,62,18,42,89,47,84,44
998,65,32,29,70,18,5,19,91,1,29,...,25,66,40,14,71,59,1,31,0,49
999,47,74,39,26,12,58,87,17,88,64,...,64,21,87,96,67,43,15,76,81,23

In [18]:
pd.options.display.max_columns

20

In [19]:
pd.options.display.max_columns=8

In [20]:
df

     0   1   2   3   ...  46  47  48  49
0    11  25  30  63  ...  78  87  67  96
1    97   9  63  70  ...  10  60  17  89
2    17  93  64  93  ...  94  63  78   6
..   ..  ..  ..  ..  ...  ..  ..  ..  ..
997  32   0  31  38  ...  89  47  84  44
998  65  32  29  70  ...   1  31   0  49
999  47  74  39  26  ...  15  76  81  23

[1000 rows x 50 columns]

In [29]:
pd.get_option("max_columns")

OptionError: Pattern matched multiple keys

In [25]:
pd.set_option("max_rows", 16)

OptionError: Pattern matched multiple keys